version: '3.9'

services:

  petflow-api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: petflow-api

    restart: always

    ports:
      - "8080:8080"

    depends_on:
      - h2db

    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:tcp://h2db:9090/h2/data/petflowdb
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.h2.Driver
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD:

      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.H2Dialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop

      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
      SPRING_JPA_OPEN_IN_VIEW: "false"

      SPRING_CACHE_TYPE: simple

      SPRINGDOC_SWAGGER_UI_PATH: /swagger
      SPRINGDOC_API_DOCS_PATH: /api-docs

    networks:
      - petflow-network

  h2db:
    image: oscarfonts/h2

    container_name: h2db

    restart: always

    ports:
      - "9090:9090"
      - "81:81"

    environment:
      H2_OPTIONS: >
        -tcp
        -tcpAllowOthers
        -tcpPort 9090
        -baseDir /h2-data

    volumes:
      - h2-data:/h2-data

    networks:
      - petflow-network

networks:
  petflow-network:
    driver: bridge

volumes:
  h2-data: